[2023-04-27T08:04:25.526+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark-example.sql_job scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-04-27T08:04:25.533+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark-example.sql_job scheduled__2023-04-26T00:00:00+00:00 [queued]>
[2023-04-27T08:04:25.534+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-27T08:04:25.534+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-27T08:04:25.534+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-27T08:04:25.546+0000] {taskinstance.py:1309} INFO - Executing <Task(SparkSqlOperator): sql_job> on 2023-04-26 00:00:00+00:00
[2023-04-27T08:04:25.551+0000] {standard_task_runner.py:55} INFO - Started process 201 to run task
[2023-04-27T08:04:25.555+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark-example', 'sql_job', 'scheduled__2023-04-26T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/spark-example.py', '--cfg-path', '/tmp/tmp141_6nio']
[2023-04-27T08:04:25.557+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask sql_job
[2023-04-27T08:04:25.612+0000] {task_command.py:389} INFO - Running <TaskInstance: spark-example.sql_job scheduled__2023-04-26T00:00:00+00:00 [running]> on host fdabfec8959b
[2023-04-27T08:04:25.675+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-example
AIRFLOW_CTX_TASK_ID=sql_job
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-26T00:00:00+00:00
[2023-04-27T08:04:25.803+0000] {spark_sql.py:177} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found

[2023-04-27T08:04:25.804+0000] {spark_sql.py:177} INFO - JAVA_HOME is not set

[2023-04-27T08:04:25.816+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_sql.py", line 97, in execute
    self._hook.run_query()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_sql.py", line 183, in run_query
    f"Cannot execute '{self._sql}' on {self._master} (additional parameters: '{cmd}'). "
airflow.exceptions.AirflowException: Cannot execute 'select 1+1' on local (additional parameters: ''). Process exit code: 1.
[2023-04-27T08:04:25.820+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=spark-example, task_id=sql_job, execution_date=20230426T000000, start_date=20230427T080425, end_date=20230427T080425
[2023-04-27T08:04:25.839+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task sql_job (Cannot execute 'select 1+1' on local (additional parameters: ''). Process exit code: 1.; 201)
[2023-04-27T08:04:25.886+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-27T08:04:25.928+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
